#!/scratch/midway2/jiaweiz/anaconda3/bin/python3
import numpy as np
from tqdm import tqdm
import argparse
import utils
import threading
import os

if __name__ == "__main__":
    # -----------------------------------------------------------------------------
    utils.time_now()

    parser = argparse.ArgumentParser()
    parser.add_argument("-s", "--save_folder", type=str,
            help="*.save folder generated by QE. Default: ./scf.save")
    parser.add_argument("-d", "--delta", type=float,
            help="delta that control local VB/CB. Default: 0.001")
    parser.add_argument("-t", "--thread", type=int,
            help="num of thread. Default: 10")
    parser.add_argument("-b", "--backup", type=int,
            help="store wfc on disk 1 or not 0 (store in memory). Default: 0")
    args = parser.parse_args()

    # default values
    if not args.save_folder:
        args.save_folder = "./scf.save"
    assert(os.path.exists(args.save_folder))
    if not args.thread:
        args.thread = 10 
    if not args.delta:
        args.delta = 0.001 
    if not args.backup:
        args.backup = 0 

    utils.delta = args.delta

    print(f"configurations:\
            \n\t{'QE save folder:':^35}{args.save_folder:^20}\
            \n\t{'delta:':^35}{args.delta:^20}\
            \n\t{'threads:':^35}{args.thread:^20}\
            ")

    # -----------------------------------------------------------------------------
    xml_file = args.save_folder + '/data-file-schema.xml'
    wfc_files = [args.save_folder + '/' + file for file in os.listdir(args.save_folder) if 'wfc' in file]

    xml_data = utils.parse_QE_XML(xml_file)
    # num of occupied bands
    nks = xml_data['nks']
    utils.numOcc = xml_data['occ']   # [nks * nbnds]
    utils.kWeights = xml_data['kweights']
    utils.tot_bands = xml_data['nbnd']
    utils.eigens = xml_data['eigen'] # [nks * nbnds]
    fft_grid = xml_data['fftw']
    fft_grid = np.array(fft_grid) // 2 + 1

    utils.ksStateZAve = np.zeros((nks, utils.tot_bands, fft_grid[2]))
    for index in range(nks):
        wfc_data = utils.parse_QE_wfc(wfc_files[index])
        ik = wfc_data['ik']
        print(f"'ik: ': {ik}, nbnd: {wfc_data['nbnd']}, npol: {wfc_data['npol']}, igwx: {wfc_data['igwx']}")

        # store and read
        if args.backup == 1:
            storeFolder = './wfc1'
            utils.storeGvec(xml_data, wfc_data, Store=True, storeFolder=storeFolder)
            for ibnd in tqdm(range(wfc_data['nbnd']), desc='read wfc from store file'):
                wfcName = storeFolder + '/wfc_r_' + str(ibnd + 1).zfill(5) + '.npy'
                evc_r = np.load(wfcName)
                utils.ksStateZAve[ik - 1, ibnd, :] = np.sum(np.absolute(evc_r) ** 2, axis=(0, 1,))
        else:
            # direct comput and store in memory
            evc_r = utils.storeGvec(xml_data, wfc_data, Store=False)
            utils.ksStateZAve[ik - 1, :, :] = np.sum(np.absolute(evc_r) ** 2, axis=(1, 2,))

    utils.lcbm = np.zeros(fft_grid[2])
    utils.lvbm = np.zeros(fft_grid[2])
    #define lock and condition
    utils.lock_list = threading.Lock()
    utils.condition_list = threading.Condition(utils.lock_list)

    num_thread = args.thread
    length_chunk = fft_grid[2] / num_thread
    a_axis_tot = list(range(fft_grid[2]))

    utils.lock_list.acquire()
    for i in range(num_thread):
        utils.z_axis_assign.append(a_axis_tot[int(i * length_chunk) : int((i + 1) * length_chunk)])

    # poison
    utils.z_axis_assign.append([])
    utils.condition_list.notify_all()
    utils.lock_list.release()

    # start thread
    threads = []
    ids = []
    for i in range(num_thread):
        ids.append(i)
        thread_id = threading.Thread(target=utils.ldos_worker, args = (ids[i],))
        threads.append(thread_id)

    for thread_id in threads:
        thread_id.start()

    for thread_id in threads:
        thread_id.join()
    # thread end
    with open('ldos.txt', 'w') as file_object:
        file_object.writelines("LVBM:\n")
        for i in range(fft_grid[2]):
            file_object.write(f'{utils.lvbm[i]:12.5f}')
            if i % 5 == 4:
                file_object.write('\n')
        file_object.write('\n\n')
        file_object.writelines("LCBM:\n")
        for i in range(fft_grid[2]):
            file_object.write(f'{utils.lcbm[i]:12.5f}')
            if i % 5 == 4:
                file_object.write('\n')
