#!/bin/bash
#SBATCH --job-name=LF
#SBATCH --output=rcc-%j.out
#SBATCH --error=rcc-%j.err
#SBATCH --time=2:00:00
#SBATCH --partition=gagalli-csl2
#SBATCH --qos=gagalli-debug
#SBATCH --account=pi-gagalli
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=48
#SBATCH --cpus-per-task=1 #increase this comensurate with number of threads

NTASKS=$(($SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES))

mpirun -np ${NTASKS} python3 -u test.py -param
# rm rcc-*
